import os
import shutil
import subprocess
import sys
from argparse import ArgumentParser, Namespace
from pathlib import Path
from typing import NamedTuple

from ruamel.yaml import YAML

from linux_arctis_manager.cli_tools import arctis_usb_info
from linux_arctis_manager.config import DeviceConfiguration
from linux_arctis_manager.constants import (DEVICES_CONFIG_FOLDER,
                                            UDEV_RULES_PATHS)
from linux_arctis_manager.systemd import ensure_systemd_unit
from linux_arctis_manager.utils import project_version

ConfigRuleset = NamedTuple(
    'ConfigRuleset',
    [
        ('vendor_id', int),
        ('product_ids', list[int]),
        ('device_name', str)
    ])

ICONS_PATH = Path().home() / '.local' / 'share' / 'icons'
ICON_PATH = ICONS_PATH / 'arctis-manager.svg'

APPLICATIONS_PATH = Path().home() / '.local' / 'share' / 'applications'
DESKTOP_WINDOW_PATH = APPLICATIONS_PATH / 'ArctisManager.desktop'
DESKTOP_SYSTRAY_PATH = APPLICATIONS_PATH / 'ArctisManagerSystray.desktop'

def sudo_it(command: list[str]) -> int:
    pkexec = shutil.which('pkexec')
    if not pkexec:
        print('pkexec not found.')
        return 250

    result = subprocess.run(["pkexec", *command], check=True)

    return result.returncode

def write_udev_rules(rules_path: Path, create_directories: bool, force_write: bool) -> int:
    run_with_sudo = False

    print('Writing udev rules...')

    if rules_path.is_dir():
        print(f'Cannot write to directory {rules_path}')
        print('Please specify a file.')

        return 1

    if create_directories:
        rules_path.parent.mkdir(parents=True, exist_ok=True)

    if not rules_path.parent.exists():
        print(f'Cannot write to {rules_path}')
        print('Parent directory does not exist.')

        return 2

    if rules_path.exists() and not os.access(rules_path, os.W_OK) \
        or not rules_path.exists() and not os.access(rules_path.parent, os.W_OK):
        print('')
        print(f"User can't write to {rules_path}.")
        print('Command will be executed with pkexec (root).')
        print('')
        input('Press Enter to continue...')

        run_with_sudo = True

    if not force_write and rules_path.exists():
        print(f'File {rules_path} already exists.')
        print('To overwrite add option --force.')

        return 3

    yaml = YAML(typ='safe')
    products: list[ConfigRuleset] = []
    for config_path in DEVICES_CONFIG_FOLDER:
        for config_file in config_path.glob('*.yaml'):
            config_yaml = yaml.load(config_file)

            config = DeviceConfiguration(config_yaml)
            products.append(ConfigRuleset(config.vendor_id, config.product_ids, config.name))

    rule_template = 'SUBSYSTEM=="usb", ENV{{DEVTYPE}}=="usb_device", ATTRS{{idVendor}}=="{idVendor}", ATTRS{{idProduct}}=="{idProducts}", MODE="0666", TAG+="uaccess"'
    rules = []
    for ruleset in products:
        rule = rule_template.format(
            idVendor=f'{ruleset.vendor_id:04x}',
            idProducts='|'.join([f'{pid:04x}' for pid in ruleset.product_ids]) if len(ruleset.product_ids) > 1 else f'{ruleset.product_ids[0]:04x}'
        )
        rules.extend(['', f'# {ruleset.device_name}', rule])

    concat_rules = '\n'.join(rules)
    file_content = f'''# Generated by Arctis Manager via lam-cli udev write-rules

ACTION=="remove", GOTO="local_end"
{concat_rules}

LABEL="local_end"'''
    
    if rules_path.exists() and rules_path.read_text().strip() == file_content.strip():
        print('Rules file is up to date, skipping write.')
        return -10

    if run_with_sudo:
        escaped_file_content = file_content.replace('"', '\\"')
        command = ["sh", "-c", f"echo \"{escaped_file_content}\" > \"{rules_path}\""]
        return sudo_it(command)
    else:
        with rules_path.open('w') as f:
            f.write(f'{file_content}\n')

    return 0

def reload_udev_rules() -> int:
    run_with_sudo = False
    if os.geteuid() != 0:
        run_with_sudo = True
    print('Reloading udev rules...')

    commands = [
        ('Reload Rules', ["udevadm", "control", "--reload-rules"]),
        ('Trigger Rules', ["udevadm", "trigger", "--subsystem-match=usb"]),
    ]
    result = 0
    for command in commands:
        print(f'Phase: {command[0]}')
        if run_with_sudo:
            result = sudo_it(command[1])
            if result:
                print('- Process failed!')
                return result
        else:
            result = subprocess.run(command[1], check=True).returncode
            if result:
                print('- Process failed!')
                return result

    return result

def write_desktop_entries() -> int:
    print('Writing desktop entries...')

    # 1. write the icon file
    ICONS_PATH.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(Path(__file__).parent.parent / 'gui' / 'images' / 'steelseries_logo.svg', ICON_PATH)

    # 2. write the desktop entries
    DESKTOP_WINDOW_PATH.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(Path(__file__).parent.parent / 'desktop' / 'ArctisManager.desktop', DESKTOP_WINDOW_PATH)
    shutil.copyfile(Path(__file__).parent.parent / 'desktop' / 'ArctisManagerSystray.desktop', DESKTOP_SYSTRAY_PATH)

    lam_gui = shutil.which('lam-gui')
    if lam_gui:
        DESKTOP_WINDOW_PATH.write_text(DESKTOP_WINDOW_PATH.read_text().replace('exec lam-gui', lam_gui))
        DESKTOP_SYSTRAY_PATH.write_text(DESKTOP_SYSTRAY_PATH.read_text().replace('exec lam-gui', lam_gui))

    DESKTOP_WINDOW_PATH.chmod(0o755)
    DESKTOP_SYSTRAY_PATH.chmod(0o755)

    return 0

def remove_desktop_entries() -> int:
    print('Removing desktop entries...')
    if ICON_PATH.exists():
        ICON_PATH.unlink()

    if DESKTOP_WINDOW_PATH.exists():
        DESKTOP_WINDOW_PATH.unlink()

    if DESKTOP_SYSTRAY_PATH.exists():
        DESKTOP_SYSTRAY_PATH.unlink()

    return 0

# ---------------------------------------------------------------------------
# Sub-command arguments.
# ---------------------------------------------------------------------------

def _add_udev_write_args(parser: ArgumentParser) -> None:
    parser.add_argument('--rules-path', default=None, type=Path,
                        help='Path to the udev rules file')
    parser.add_argument('--create-directories', action='store_true',
                        help='Create parent directories if missing')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite existing rules file')
    parser.add_argument('--reload', action='store_true',
                        help='Reload udev rules after writing')


# ---------------------------------------------------------------------------
# Runner helpers.
# ---------------------------------------------------------------------------

def _run_udev_write(args: Namespace) -> int:
    rules_path = args.rules_path if args.rules_path else next(
        (Path(p) for p in UDEV_RULES_PATHS if Path(p).parent.is_dir()), None
    )
    if not rules_path:
        print('No valid rules path found. Please specify one with --rules-path.')
        return 1

    result = write_udev_rules(rules_path, args.create_directories, args.force)
    if result > 0:
        return result

    if args.reload and result == 0:
        return reload_udev_rules()

    return 0


def _run_desktop_write(_: Namespace) -> int:
    return write_desktop_entries()


def _run_setup(args: Namespace) -> int:
    args.force = True
    args.reload = True

    fns = [_run_udev_write, _run_desktop_write]
    for fn in fns:
        result = fn(args)
        if result != 0:
            return result
    
    print('Enabling systemd service...')
    ensure_systemd_unit(True, True)

    desktop_filename = 'ArctisManagerSystray.desktop'
    src_dir = Path.home() / '.local' / 'share' / 'applications' / desktop_filename

    if args.systray_autostart:
        print('Enabling systray autostart...')
        symlink_path = Path.home() / '.config' / 'autostart' / desktop_filename
        symlink_path.parent.mkdir(parents=True, exist_ok=True)

        if symlink_path.exists():
            symlink_path.unlink()

        result = subprocess.run(['ln', '--symbolic', f'{src_dir}', f'{symlink_path}'], check=True).returncode
        if result != 0:
            return result
        
    if args.start_now:
        print('Launching systray application...')

        if shutil.which('kioclient'):
            result = subprocess.run(['kioclient', 'exec', f'{src_dir}'], check=True).returncode
        elif shutil.which('gtk-launch'):
            result = subprocess.run(['gtk-launch', desktop_filename], check=True).returncode
        else:
            print('No known desktop environment autostart helper found, could not launch systray...')
            result = 0

        if result != 0:
            return result

    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = ArgumentParser(description=f'Arctis Manager CLI v {project_version()}')
    subparsers = parser.add_subparsers(dest='command', required=True)

    # -- udev ----------------------------------------------------------------
    udev_parser = subparsers.add_parser('udev', help='UDEV rules')
    udev_subparsers = udev_parser.add_subparsers(dest='action', required=True)

    write_parser = udev_subparsers.add_parser('write-rules', help='Write the udev rules')
    _add_udev_write_args(write_parser)

    udev_subparsers.add_parser('reload-rules', help='Reload the udev rules')

    # -- desktop -------------------------------------------------------------
    desktop_parser = subparsers.add_parser('desktop', help='Desktop entries management')
    desktop_subparsers = desktop_parser.add_subparsers(dest='action', required=True)
    desktop_subparsers.add_parser('write', help='Write the desktop entries')
    desktop_subparsers.add_parser('remove', help='Remove the desktop entries')

    # -- setup ---------------------------------------------------------------
    setup_parser = subparsers.add_parser(
        'setup',
        help='Full setup: write udev rules and desktop entries'
    )
    setup_parser.add_argument('--systray-autostart', action='store_true', help='Start the systray app on login')
    setup_parser.add_argument('--start-now', action='store_true', help='Start the application immediately')

    _add_udev_write_args(setup_parser)

    # -- tools ---------------------------------------------------------------
    tools_parser = subparsers.add_parser('tools', help='Reverse engineering tools')
    usb_devices_subparser = tools_parser.add_subparsers(dest='action', required=True)
    arctis_devices_parser = usb_devices_subparser.add_parser(
        'arctis-devices',
        help='List important Arctis device(s) information, like HID interfaces, alternate configs, etc.'
    )
    arctis_devices_parser.add_argument('--vendor-id', default=0x1038, type=int)

    args = parser.parse_args()

    if args.command == 'udev':
        if args.action == 'write-rules':
            sys.exit(_run_udev_write(args))
        elif args.action == 'reload-rules':
            sys.exit(reload_udev_rules())
    elif args.command == 'desktop':
        if args.action == 'write':
            sys.exit(_run_desktop_write(args))
        elif args.action == 'remove':
            sys.exit(remove_desktop_entries())
    elif args.command == 'setup':
        sys.exit(_run_setup(args))
    elif args.command == 'tools':
        if args.action == 'arctis-devices':
            sys.exit(arctis_usb_info(args.vendor_id))

if __name__ == '__main__':
    main()
